matrix:
  include:
    - os: linux
      env: NODE_VERSION=0.10
    - os: linux
      env: NODE_VERSION=0.12
script:
  - tools/test-travis.sh
sudo: false
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
    - flvtool2